### ISSUE TITLE
Error: The argument type 'HTMLStyleElement' can't be assigned to the parameter type 'JSAny'.

### ISSUE THREAD

**Issue by imeDevelopers** [dart-lang/web#128]
Error:

../../flutter/packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart:118:33:
Error: The argument type 'HTMLStyleElement' can't be assigned to the parameter type 'JSAny'.
 - 'HTMLStyleElement' is from 'package:web/src/dom/html.dart' ('../../flutter/.pub-cache/hosted/pub.dev/web-0.4.0/lib/src/dom/html.dart').
 - 'JSAny' is from 'dart:_js_types'.
      web.document.head!.append(styleElement);

-------------------------------------------

Solution:

file: ..\flutter\packages\flutter\lib\src\widgets\_platform_selectable_region_context_menu_web.dart

line: 118

change:
web.document.head!.append(styleElement);

with:
web.document.head!.append(styleElement.toJSBox);

Thank you.

**Comment by kevmoo** [comment]
This might be a bug in Flutter.

What's the version of Flutter you're on here?

CC @srujzs

**Comment by imeDevelopers** [comment]
@kevmoo 
3.16.5 Flutter SDK
3.2.3 (Flutter) Dart SDK
Package: web
Version: 0.4.0

This was a flutter web application build, both debug and release.

**Comment by imeDevelopers** [comment]
Windows 11

**Comment by srujzs** [comment]
I thought you couldn't use `0.4.0` before https://github.com/flutter/flutter/commit/d8ffc7390cc696d14e78d7a9bd9c83fbe0182512 (which was landed after 3.16.5)? It should have been pinned to `0.3.0` before this CL. Shouldn't users get a different error here due to versions not resolving?

Also FYI:

> web.document.head!.append(styleElement.toJSBox);

`toJSBox` wraps the object in a literal, which you don't want here. `toJSBox` is meant for Dart (not JS/interop) objects to be passed around in the same Dart runtime. The fix (which the above commit contains) is a cast to `JSAny`.

**Comment by imeDevelopers** [comment]
@srujzs 

You maybe right,
but this is what happened for me and here's how I solved the problem for the future visitors, I wasn't able to build my app!

It maybe a temporary solution, but it still works until the new versions.

Thank you.

**Comment by dimiril** [comment]
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../../../flutter/packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart:118:33: Error: The argument type 'HTMLStyleElement' can't be assigned to the parameter type 'JSAny'.
 - 'HTMLStyleElement' is from 'package:web/src/dom/html.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.4.0/lib/src/dom/html.dart').
 - 'JSAny' is from 'dart:_js_types'.
      web.document.head!.append(styleElement);
                                ^
Failed to compile application.

**Comment by srujzs** [comment]
I wonder if it's a matter of changing your version dependencies per https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages. Maybe the `package:web` dependency in your pubspec should be `^0.3.0`? Can either of you share your pubspec? Thanks!

**Comment by kevmoo** [comment]
You have to cast `as JSAny` is if you want to span between v0.3.0 and v0.4.0 – it's tricky as we get this working!

**Comment by srujzs** [comment]
My apologies, I guess the right version constraint to replace your existing constraint with here is `web: >=0.3.0 <0.5.0` since `^0.3.0` won't cover `0.4.0`. It's a bit strange that `flutter_test` uses `0.4.0` even though the Flutter SDK is using `0.3.0`. I would expect them to use the same version - I'll need to dig into this a bit deeper.

**Comment by srujzs** [comment]
Okay, using a Flutter `3.16.5` and constraint `web: 0.4.0` gives me:

```
Resolving dependencies...
Note: web is pinned to version 0.3.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because every version of flutter_test from sdk depends on web 0.3.0 and testweb depends on web 0.4.0, flutter_test from sdk is forbidden.
So, because testweb depends on flutter_test from sdk, version solving failed.
```

which is what I would expect, and not `0.4.0` like your error has. This is resolved when I set the constraints to `web: '>=0.3.0 <0.5.0'` or `web: 0.3.0` (or any other combination that includes `0.3.0`) in my local package. There may be something weird going on with your Flutter versions/paths, but I can't say for sure. My `flutter --version`:

```
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (7 days ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
```

**Comment by AwaisQazii** [comment]
how to resolve this issue @srujzs

**Comment by srujzs** [comment]
You'll likely want to give a version range for `package:web` here so that it's compatible with Flutter: `web: '>=0.3.0 <0.5.0'` or directly pin `web: 0.3.0`.

**Comment by AwaisQazii** [comment]
I've downgraded flutter version to 3.16.0, it worked fine

**Comment by bsz0206** [comment]
pinning the web version to 3.0 or downgrading flutter to 3.16.0 is just a temporary fix. IS any better fix in the forecast?

**Comment by srujzs** [comment]
Flutter requires this pinning per their policy: https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages#how-does-the-pinning-affect-me for any packages they use.

However, we did remove `package:web` from Flutter altogether in https://github.com/flutter/flutter/commit/2407f699e935d09d6d56fb9005f210966aa1debd so users don't have to be stuck on an old version of `package:web`. It looks like that change should be available in Flutter `3.18.0`.

**Comment by dmontilla** [comment]
@srujzs I did what you mention but not working, is any other solution for this error? I´m pinning the web version to 3.0 in wrong way?

**Comment by srujzs** [comment]
Can you share what you've tried/your `pubspec.yaml`/the errors you're coming across?

**Comment by mamaly12** [comment]
This is my pubspec.yaml, I receive the same error when I run my application on web:

```
name: test
description: test

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
 sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  dio: ^5.4.0
  image_picker: 1.0.7
  file_picker: ^6.1.1
  persian_datetime_picker : ^2.6.0
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  equatable: ^2.0.5
  uuid: ^4.3.3
  very_good_analysis: ^5.1.0
  intl: ^0.18.1
  formz: ^0.6.1
  mocktail: ^1.0.3
  flutter_bloc: ^8.1.3
  flutter_localizations:
   sdk: flutter
  sqflite: ^2.3.0
  idb_shim: ^2.3.1
  dropdown_search: ^5.0.6
  bloc_test: ^9.1.5
  font_awesome_flutter: 10.7.0
  bloc_concurrency: ^0.2.3
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logging: ^1.2.0
  tuple: ^2.0.2
  web_socket_channel: ^2.4.3
  message_pack_dart: ^2.0.1
  async: ^2.11.0
  pool: ^1.5.1
  sse: ^4.1.4
  web: ^0.4.2
dev_dependencies:
  collection: ^1.15.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
      # An image asset can refer to one or more resolution-specific "variants", see
      # https://flutter.dev/assets-and-images/#resolution-aware

      # For details regarding adding assets from package dependencies, see
      # https://flutter.dev/assets-and-images/#from-packages

      # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: IRANSans
      fonts:
        - asset: fonts/IRANSans(FaNum).ttf
        - asset: fonts/IRANSans(FaNum)_Bold.ttf
        - asset: fonts/IRANSans(FaNum)_Light.ttf
        - asset: fonts/IRANSans(FaNum)_Medium.ttf
    - family: Far_Nazanin
      fonts:
        - asset: fonts/Far_Nazanin.ttf
    #
    #         weight: 700
    #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
